version: '3'

services:
  ##### Catalog Services - Start #####
  ### For YBDB - Start ###
  # catalog-db:
  #   platform: linux/amd64
  #   image: yugabytedb/yugabyte:latest
  #   container_name: rtdl_catalog-db
  #   volumes:
  #     - ./storage/rtdl-catalog-db_data:/home/yugabyte/yb_data
  #   command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
  #   expose:
  #     - 5433
  #   # ports:
  #   #   - 5433:5432
  #   ports:
  #     - 5433:5433
  #   healthcheck:
  #       test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 12

  # catalog:
  #   platform: linux/amd64
  #   image: rtdl/hive-metastore
  #   container_name: rtdl_catalog
  #   expose:
  #     - 9083
  #   ports:
  #     - 9083:9083
  #   volumes:
  #     - ./scripts/entrypoint-run.sh:/entrypoint.sh
  #     - ./conf/metastore-site.ybdb.xml:/opt/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
  #   entrypoint: sh -c "chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh && sh -c /entrypoint.sh"
  #   depends_on:
  #     catalog-db:
  #       condition: service_healthy
  ### For YBDB - End ###

  ### For Postgres - Start ###
  catalog-db:
    platform: linux/amd64
    image: postgres:latest
    container_name: rtdl_catalog-db
    volumes:
      - ./storage/rtdl-catalog-db_data:/var/lib/postgresql/data
    expose:
      - 5432
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 12

  catalog:
    platform: linux/amd64
    image: rtdl/hive-metastore
    container_name: rtdl_catalog
    expose:
      - 9083
    ports:
      - 9083:9083
    volumes:
      - ./scripts/entrypoint-run.sh:/entrypoint.sh
      - ./conf/metastore-site.postgres.xml:/opt/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
    user: root
    command: bash -c "chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh && bash -c /entrypoint.sh"
    depends_on:
      catalog-db:
        condition: service_healthy
  ### For Postgres - End ###
  ##### Catalog Services - End #####
